### ISSUE TITLE
Food Content

### ISSUE THREAD

**Issue by blester125** [r-three/licensed-pile#11]
Domain: Recipes/Food Blogs

In general, recipes (as a list of ingredients) aren't copywritable, but the prose that comes with them often are.

- [ ] Foodist [CC is mentioned in TOS](https://www.foodista.com/static/legal)

**Comment by StellaAthena** [comment]
> You may copy, modify, and redistribute Foodista content marked with the Creative Commons License, as long as you meet the the terms of the Creative Commons License. The license allows Foodista content to be used freely. Allowing free republication of our content helps achieve Foodista's mission by offering recipes and cooking information to even more people. In addition, our license allows for the creation of derivative works under the same license.
> 
> Our attribution requirements are easily satisfied. For internet re-publishing, a direct link back to the page AND prominent text stating the material came from "Foodista.com – The Cooking Encyclopedia Everyone Can Edit" satisfies our attribution requirement. For offline distribution, prominent attribution to "Foodista.com - The Cooking Encyclopedia Everyone Can Edit" will suffice.

The CC license they refer to here is CC-BY-3.0 so this is good to go.
