### ISSUE TITLE
Project Gutenberg

### ISSUE THREAD

**Issue by blester125** [r-three/licensed-pile#2]
Domain: Old Books
~10K pages

Data at https://gutenberg.org/. Data is mostly raw text, probably need to remove some project gutenberg header/footer text.

**Comment by StellaAthena** [comment]
@blester125 am I correct in assuming that this is approximately finished? We'll need to rerun it in the future to get any new books, and there's a few books that may need to be tracked down, but this is basically done?

**Comment by blester125** [comment]
Yeah the code is done, and this can be closed.

The only thing that could be worth someone looking into eventually is if there are any books on pg that where published before 1924 but after 1919 that is still listed as copyrighted and therefore skipped.
