### ISSUE TITLE
Datasets from SILOLM

### ISSUE THREAD

**Issue by blester125** [r-three/licensed-pile#20]
Domain: Various

We may need to double check their pre-processing and decide if we want to update them.

- [ ] Pile of Law
- [ ] Case Law Access Project
- [ ] Github from RedPajama
- [ ] HackerNews
- [ ] Ubuntu IRC
- [x] Stackexchange from RedPajama
- [ ] Stackoverflow corpus from Kaggle
- [ ] Deepmind Mathematics
- [ ] AMPS dataset
- [ ] ArXiv abstracts
- [x] S2ORC (scientific papers)
- [x] Gutenberg Corpus (PG19)
- [ ] MOT corpus (News)
- [ ] Wikinews
- [ ] Wikipedia from RedPajama

**Comment by StellaAthena** [comment]
Closing as merged into https://github.com/r-three/licensed-pile/issues/46
