### ISSUE TITLE
Biodiversity Heritage Library

### ISSUE THREAD

**Issue by nkandpa2** [r-three/licensed-pile#24]
Digital library for works on biodiversity. Total collection is ~60M pages but from inspecting their bulk download about one third of this is public domain. Bulk downloads available here: https://about.biodiversitylibrary.org/tools-and-services/developer-and-data-tools/#x--MODS

**Comment by nkandpa2** [comment]
An update after filtering the data to only public domain books.

Number of books: 155,626
Size on disk: 169 GB
Number of books per language:
```
{
    "GER": 15824,
    "ENG": 115025,
    "LAT": 3312,
    "FRE": 11964,
    "SPA": 1548,
    "DAN": 332,
    "POR": 361,
    "SWE": 1084,
    "ITA": 2332,
    "null": 7230,
    "UND": 181,
    "DUT": 1049,
    "RUS": 788,
    "MUL": 53,
    "NOR": 327,
    "JPN": 676,
    "HUN": 226,
    "CAT": 32,
    "CHI": 10,
    "RUM": 28,
    "CZE": 74,
    "FIN": 8,
    "ICE": 2,
    "SCR": 26,
    "ARA": 7,
    "POL": 46,
    "GSW": 1,
    "GRE": 5,
    "MLG": 1,
    "TAM": 2,
    "TON": 7,
    "TAT": 1,
    "UKR": 10,
    "THA": 1,
    "GRC": 4,
    "FRO": 3,
    "URD": 1,
    "GLE": 5,
    "KAL": 1,
    "MAP": 5,
    "MAY": 3,
    "WAS": 4,
    "BUR": 1,
    "VOL": 4,
    "SAI": 3,
    "HRV": 5,
    "YID": 2,
    "ROH": 1,
    "OTA": 1,
    "SCC": 3,
    "IND": 2,
    "GUJ": 1,
    "GMH": 2,
    "HAW": 1,
    "TUR": 1,
    "GLA": 1,
    "WEL": 1
}
```

**Comment by StellaAthena** [comment]
@nkandpa2 It looks like you've added some code, can you update us as to the status of this?

**Comment by nkandpa2** [comment]
The code for collecting this source is completed and I've tested it on the full dataset with no issues. I'll go ahead and close this for now.
