### ISSUE TITLE
NASA ADS

### ISSUE THREAD

**Issue by nkandpa2** [r-three/licensed-pile#29]
NASA Astrophysical Data System

**Comment by lintangsutawika** [comment]
Can take a look for this one.

**Comment by lintangsutawika** [comment]
Seems like we can't use this.

I had a look at the Terms and Condition
https://ui.adsabs.harvard.edu/help/terms/

It's not under a creative commons or any open licensed. 

> Full-text articles and abstracts of papers available from the ADS databases are copyrighted by the respective publishers and are subject to all applicable copyright protection under the laws of the United States and other countries. The reproduction of full-text articles or abstracts requires express written permission from the publisher.

The terms of use for NASA ADS don't seem scrape friendly.
> Users may not perform systematic downloads of articles, abstracts, or tables of contents for any purpose, whether commercial or not, without the written permission of the ADS. This includes indiscriminate, mass downloads of search results and the use of robots.

**Comment by craffel** [comment]
Thanks for making note of this.
