### ISSUE TITLE
Stack Exchange

### ISSUE THREAD

**Issue by blester125** [r-three/licensed-pile#3]
Domain: Technical Question-Answer and Discussion
~10m pages
English

@craffel said he has a stack exchange parser to use.

SiloLM paper also used stack exchange, we need to look at there data preprocessing and decide if we want to use theirs or re-do it.

Design Considerations:
 * Questions can have multiple answers
   * Do you create multiple (q, a) pairs with the same question for each answer?
   * Do you create a single (q, a1, a2, ...) document?
     * Do you sort by ranking or similar?
 * Where do we put the comments in a document?
 * Stack Exchange can have edits that change text/author information opaquely, thus some comments become non sequiturs when something they referenced changes

**Comment by StellaAthena** [comment]
@craffel Is there anything that remains to be done here, or is this complete?

**Comment by craffel** [comment]
@blester125 took over migrating the code, and it's mostly migrated. I think the README needs updating, otherwise looks mostly done. https://github.com/r-three/licensed-pile/tree/main/stackexchange
