### ISSUE TITLE
AMPS

### ISSUE THREAD

**Issue by nkandpa2** [r-three/licensed-pile#30]

**Comment by nkandpa2** [comment]
@StellaAthena is this referring to the AMPS pre-training dataset from https://github.com/hendrycks/math?

**Comment by StellaAthena** [comment]
Yes

**Comment by haileyschoelkopf** [comment]
Hoping to port AMPS this week.

**Comment by craffel** [comment]
The Khan Academy exercises are CC-BY-NC-SA licensed, which is not a license we include, so would need to be excluded. I can't find much information about the Mathematica files; the MATH dataset repo has an MIT license the Mathematica exercises are all based on files that are not in the repo and so I can't determine a license. Can anyone else find any license information? If not, we should close this.

**Comment by StellaAthena** [comment]
I looked and couldn't find the license either. I think we should probably exclude this data.
