### ISSUE TITLE
Meta: Issue labels

### ISSUE THREAD

**Issue by craffel** [r-three/licensed-pile#35]
Can someone make a set of labels to apply to issues? Like, needs a contributor, etc.

**Comment by craffel** [comment]
- Needs an owner
- Easy/medium/hard
- Status (raw obtained, v0 without filtering, filtered)
- Needs migration (from some previous code/source)

**Comment by StellaAthena** [comment]
@craffel It's best to manage these kinds of fields via a project, but projects have been migrated out of the repo-level management and to the org-level management. If you create a project for this work I can set it up.

**Comment by craffel** [comment]
The "edit labels" view seems totally sufficient, what does making a project buy us?

**Comment by StellaAthena** [comment]
> The "edit labels" view seems totally sufficient, what does making a project buy us?

1. Levels are a lot less of a fuss (high/medium/low priority)
2. It seems like the thing you're supposed to do and I typically default to doing that.
