### ISSUE TITLE
Create contributing.md

### ISSUE THREAD

**Issue by craffel** [r-three/licensed-pile#36]

**Comment by StellaAthena** [comment]
Hi

**Comment by li-yingfei** [comment]
Could someone add me to the project here?

**Comment by craffel** [comment]
Loosely it seems like what we should stipulate up-front is that a given source should
- Have its own subdirectory.
- Have code for downloading/crawling, processing, and writing out the data. etc. Basically go from nothing to processed data.
- Have a run.sh file that downloads, processes, and writes out. The run.sh file should have a --test mode that only runs on a small fraction of the data.
- Have a README.md describing what is done.
We aren't going to worry about forcing people to use a set of specific tools or specifying train/validation/test splits at this point. Then, we can just point to an example source (and we should have an example source soon-ish, just need to write the writing-out part now).

**Comment by craffel** [comment]
Regarding how much preprocessing should be done, we are assuming that all source-specific cleaning is done as part of preprocessing (e.g. parsing mediawiki markup/tex source/whatever, removing headers/footers...), but that non-source-specific processing (e.g. toxicity detection, quality filtering) is not.

**Comment by craffel** [comment]
Regarding license laundering, if when preparing a source you notice that a lot of the content is copyrighted but is listed by someone (who is not the owner of the content) as having a permissive license, please flag it and we will discuss it and consider removing the (sub-)source.

**Comment by craffel** [comment]
We should use Ubuntu IRC logs as an example for this.
