### ISSUE TITLE
Meta: Data Storage

### ISSUE THREAD

**Issue by soldni** [r-three/licensed-pile#37]
Figure out storage: S3? R2? AI2 could maybe provide a bucket?

**Comment by StellaAthena** [comment]
@soldni For now, we are not planning on downloading the data in bulk as we would need to rescrape it in the future anyways. We are just downloading a small amount of data that can be used to write the code.

Ultimately I was thinking we'd just put it all on HF, though EleutherAI also has plenty of storage.
