### ISSUE TITLE
Khan Academy

### ISSUE THREAD

**Issue by lintangsutawika** [r-three/licensed-pile#40]
https://www.khanacademy.org
Courses are listed with license [Creative Commons Attribution/Non-Commercial/Share-Alike](http://creativecommons.org/licenses/by-nc-sa/3.0)

All videos have transcripts, so that could be scraped.

**Comment by StellaAthena** [comment]
NC-SA means that not only can this data not be used for commercial purposes, but anything it's mixed with can't either. That's not suitable for our project.
