### ISSUE TITLE
Open Arizona

### ISSUE THREAD

**Issue by lintangsutawika** [r-three/licensed-pile#41]
> Open Arizona is a portal of open-access titles from the University of Arizona Press. We are adding new content to the site monthly. Recently, we added titles in anthropology, archaeology, border studies, and Latin American studies. Please check back frequently to see our latest offerings.

https://open.uapress.arizona.edu/

Collection of 124 contemporary books published under CC BY-NC-ND 4.0

**Comment by StellaAthena** [comment]
NC-ND means "non-commerical, no derivatives" and is not suitable for this project.
