### ISSUE TITLE
Ubuntu IRC

### ISSUE THREAD

**Issue by blester125** [r-three/licensed-pile#5]
Domain: Technical Chat
Moderated
Data is text

"The content of all Ubuntu channels, whether official logs or otherwise, are considered to be in the public domain."

There are a lot of interleaved dialogues in datasets like this. They are hard to disentangle. [Some work](https://aclanthology.org/P19-1374/) has been done where (IIRC) they manually annotated conversations within ubuntu IRC. Code they used from the previous paper https://jkk.name/irc-disentanglement/

Are there other IRC chats/forms like this? For example ArchWiki? Linux Kernel Development Mailing List (might be too much of a "toxic" source tho, lol)?

**Comment by StellaAthena** [comment]
Is this finished?

**Comment by craffel** [comment]
@blester125 migrated the code, looks like it needs a little more cleanup/README work

**Comment by blester125** [comment]
When someone is quoted in a chat, should we include them as an author for that chat? They wrote content that is in the chat but they didn't decide to have that content in the chat?

Finishing up the readme soon

**Comment by craffel** [comment]
Do you mean they are quoted from another chat room, i.e. they didn't otherwise participate in the chat room during the logging period?

**Comment by blester125** [comment]
In the example I found they were either quoted from another chat room or from a previous day (and thus a different document in our formatting), but yes, they didn't otherwise participate in the chat room during the logging period (a day).

**Comment by craffel** [comment]
Hm, I might guess that quoting someone would be considered "fair use" (Wikipedia includes quotes on their CC-BY pages under the fair use doctrine https://en.wikipedia.org/wiki/Wikipedia:Reusing_Wikipedia_content#Fair_use_materials_and_special_requirements). In addition the original quotes content is in the public domain. But I think if it's easy to detect we might as well include them?

**Comment by craffel** [comment]
For the time being I think we can put aside the quoting issue.

**Comment by blester125** [comment]
Sounds good. With that, I think we can close this issue as the fetching and processing code is checked in. If anyone wants to give it a once over that would be useful.
